PROGRAM MAIN
VAR
    TestEdgeDetection_sensor1: BOOL;
    TestEdgeDetection_sensor2: BOOL;
    TestEdgeDetection_pushButton: BOOL;
    TestEdgeDetection_startSignal: BOOL;
    TestEdgeDetection_stopSignal: BOOL;
    TestEdgeDetection_toggleOutput: BOOL;
    TestEdgeDetection_pulseOutput: BOOL := FALSE;
    R_TRIG_Instance1: R_TRIG;
    F_TRIG_Instance2: F_TRIG;
    R_TRIG_Instance3: R_TRIG;
    R_TRIG_Instance4: R_TRIG;
    F_TRIG_Instance5: F_TRIG;
END_VAR