import { inject } from "langium";
import {
  createDefaultModule,
  createDefaultSharedModule,
  type DefaultSharedModuleContext,
  type LangiumSharedServices,
} from "langium/lsp";
import { BcsEngineeringGeneratedSharedModule } from "./generated/module.js";
import {
  BCSControlGeneratedModule,
  BCSHardwareGeneratedModule,
} from "../language-server/generated/module.js";
import {
  BCSHardwareLangModule,
  BCSHardwareLangServices,
} from "./bcs-hardware-lang-module.js";
import {
  BCSControlLangModule,
  BCSControlLangServices,
} from "./bcs-control-lang-module.js";
import { registerBCSHardwareValidationChecks } from "./bcs-hardware-lang-validator.js";
import { registerBCSControlValidationChecks } from "./bcs-control-lang-validator.js";

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createBcsEngineeringServices(
  context: DefaultSharedModuleContext
): {
  shared: LangiumSharedServices;
  bcsControl: BCSControlLangServices;
  bcsHardware: BCSHardwareLangServices;
} {
  const shared = inject(
    createDefaultSharedModule(context),
    BcsEngineeringGeneratedSharedModule
  );
  const bcsControl = inject(
    createDefaultModule({ shared }),
    BCSControlGeneratedModule,
    BCSControlLangModule
  );
  const bcsHardware = inject(
    createDefaultModule({ shared }),
    BCSHardwareGeneratedModule,
    BCSHardwareLangModule
  );
  shared.ServiceRegistry.register(bcsControl);
  shared.ServiceRegistry.register(bcsHardware);
  registerBCSControlValidationChecks(bcsControl);
  registerBCSHardwareValidationChecks(bcsHardware);
  if (!context.connection) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    shared.workspace.ConfigurationProvider.initialized({});
  }
  return { shared, bcsControl, bcsHardware };
}
