name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Clean install with npm ci
        run: |
          rm -rf node_modules package-lock.json
          npm ci

      - name: Build and Validate
        run: |
          npm run build:clean
          npm run validate-exports || echo "Skipping validate-exports"

      - name: Run tests
        run: npm test
